### ISSUE TITLE
create front-end user interface for Landing page, Login page, Sign in  page, and Password recovery page 

### ISSUE THREAD

**Issue by jugginedwards** [BuildForSDGCohort2/Team-321-group-a-Frontend#2]
1. Create frontend using React.js  

2. Kindly find UI design model and ensure that you implement pages as shown in the UI design representations

3. Perform functionality test and confirm each page has the required functions effected

4. Test for performance and optimize efficiency of code

**Comment by Ndife** [comment]
I'll work on this.

**Comment by ifybrian** [comment]
@Ndife `

**Comment by ifybrian** [comment]
Y

**Comment by ifybrian** [comment]
@Ndife i have pushed the code i have to the repo... Check it out

**Comment by jugginedwards** [comment]
Good job guys!
